test("run help throw no exception", () => {

});
